# Generated by Django 5.2.4 on 2025-11-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id_cuadrilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cuadrilla', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='Activo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.departamento')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas_lideradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
