# Generated by Django 5.2.4 on 2025-11-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
                ('state', models.CharField(default='Activo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Sin título', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=300, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=20)),
                ('state', models.CharField(default='Activo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to='users.cuadrilla')),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.estadosolicitud')),
                ('id_territorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_territorial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField()),
                ('state', models.CharField(default='Activo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multimedia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('archivo', models.FileField(upload_to='multimedia/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(default='Activo', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.respuesta')),
                ('id_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests.solicitud')),
            ],
        ),
    ]
