# Generated by Django 5.2.7 on 2025-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadosolicitud",
            name="nombre_estado",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
